plugins {
    id "com.android.application"
}

android {
    namespace "com.pepea.siteview"
    compileSdk 35

    defaultConfig {
        applicationId "com.pepea.siteview"
        minSdk 26
        targetSdk 35
        versionCode 23
        versionName "2.1.0"
    }

    flavorDimensions "navigation"

    productFlavors {
        skynet {
            dimension "navigation"
            buildConfigField "boolean", "POINTER_ENABLED", "true"
        }
        cable {
            dimension "navigation"
            applicationId "com.pepea.cable"
            versionCode 1
            versionName "1.0.0"
            buildConfigField "boolean", "POINTER_ENABLED", "false"
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
