plugins {
    id "com.android.application"
}

android {
    namespace "com.pepea.siteview"
    compileSdk 35

    defaultConfig {
        applicationId "com.pepea.siteview"
        minSdk 26
        targetSdk 35
        versionCode 23
        versionName "2.1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
